### ISSUE TITLE
absolute positioning

### ISSUE THREAD

**Issue by mstancombe** [mstancombe/HTML-Renderer#12]
position:absolute doesn't seem to be supported.
-Add a test page that shows this
-Implement

https://developer.mozilla.org/en-US/docs/Web/CSS/position#absolute

tldr for a short version:
-take box out of flow
-move box to top left of nearest fixed/absolute/relative positioned ancestor
-move box according to top/left.

**Comment by mstancombe** [comment]
@alfattack can you see if this is feasible?

**Comment by alfattack** [comment]
PR [here](https://github.com/mstancombe/HTML-Renderer/pull/13)
